### ISSUE TITLE
Firefox update to 133 broke buttons

### ISSUE THREAD

**Issue by alisson3000br** [vinceliuice/WhiteSur-gtk-theme#1180]
just updated firefox and looks like this 

![Screenshot from 2024-11-26 13-42-43](https://github.com/user-attachments/assets/1291e383-1ffd-48bb-8f47-492ab1f18fa9)

Thanks

**Comment by LifeDreamer24** [comment]
Same here.

**Comment by alisson3000br** [comment]
also when click the address bar 

![Screenshot from 2024-11-26 17-51-29](https://github.com/user-attachments/assets/bc164599-1dc7-454e-9b24-0d275de8187b)

**Comment by AtticusZeller** [comment]
+1,
![image](https://github.com/user-attachments/assets/2b6f554c-c5ac-4aba-a616-d2e031b95dad)

**Comment by nicolas-oliveira** [comment]
It seems that only the buttons and the size of the url when clicking on it broke its behavior in the firefox update

![Captura de tela de 2024-11-27 09-41-05](https://github.com/user-attachments/assets/802d4680-cf9f-4733-b9fd-d1ed40aebe6a)
![image](https://github.com/user-attachments/assets/c266893d-0a93-4c78-84ad-4ce82d7ef383)

Maybe it's just me, but the tabs when they play sound have the wrong colors too

![Captura de tela de 2024-11-27 09-40-54](https://github.com/user-attachments/assets/40a40da7-fd45-44a4-8938-196a2156b86f)

**Comment by rijaluddina** [comment]
the problem that happened to me was like this
![Screenshot from 2024-11-28 03-43-03](https://github.com/user-attachments/assets/8ce4c40e-0099-49d3-b049-65cade464ce0)

**Comment by Neelakandan-A** [comment]
Me too, please fix soon

![Screenshot_2024-11-29_02-42-06](https://github.com/user-attachments/assets/d0308b0b-8e0f-4ab6-b43f-0b0b53cb9676)

**Comment by AtticusZeller** [comment]
thank you！

**Comment by rijaluddina** [comment]
this issue is not resolved for me

[Screencast from 2024-11-29 21-44-48.webm](https://github.com/user-attachments/assets/551fbc89-ed30-482f-91c7-3ad8ca0ddd7d)

so I need to add a little fix of my own to the customChrome.css file

```css
#urlbar[breakout][breakout-extend] {
  & > .urlbar-input-container {
    height: var(--urlbar-height) !important;
    padding-block: 1px !important;
    padding-inline: 1px !important;
    transition: none !important;
  }
}

#urlbar[breakout][breakout-extend] {
  width: var(--urlbar-width) !important;
  margin-inline-start: 0px !important;
  margin-block-start: calc(
    (var(--urlbar-container-height) - var(--urlbar-height)) / 2
  ) !important;
}
```

**Comment by w1th0ut** [comment]
> this issue is not resolved for me
> Screencast.from.2024-11-29.21-44-48.webm
> 
> so I need to add a little fix of my own to the customChrome.css file
> 
> ```css
> #urlbar[breakout][breakout-extend] {
>   & > .urlbar-input-container {
>     height: var(--urlbar-height) !important;
>     padding-block: 1px !important;
>     padding-inline: 1px !important;
>     transition: none !important;
>   }
> }
> 
> #urlbar[breakout][breakout-extend] {
>   width: var(--urlbar-width) !important;
>   margin-inline-start: 0px !important;
>   margin-block-start: calc(
>     (var(--urlbar-container-height) - var(--urlbar-height)) / 2
>   ) !important;
> }
> ```

thanks it works, for anyone who want to change the close, minimize, and restore down button on left side (default from Whitesur is right), add this code to customChrome.css file

```css
:root {
    --tabs-toolbar-navbar-overlap: 0px;
}

#titlebar {
    -moz-box-ordinal-group: 1; /* Pindahkan Titlebar ke urutan pertama */
}

#TabsToolbar {
    -moz-box-ordinal-group: 2; /* TabsToolbar pindah ke urutan kedua */
}

.titlebar-buttonbox-container {
    position: fixed;
    left: 0;
    top: 0;
    height: var(--tab-min-height);
    display: flex;
    align-items: center;
}

.titlebar-button {
    margin: 0 2px;
}
```

![Screenshot from 2024-11-30 01-31-27](https://github.com/user-attachments/assets/6509bd65-de09-4a5f-a98d-1d4759868ef2)
