### ISSUE TITLE
Suggestion for Improved Workspace Switcher OSD Design

### ISSUE THREAD

**Issue by AB-boi** [vinceliuice/WhiteSur-gtk-theme#1306]
Firstly, thank you for creating and sharing the WhiteSure theme! It’s a fantastic theme. Your work is greatly appreciated.

I would like to bring up a potential improvement regarding the **Workspace Switcher OSD** design in the theme. Currently, the OSD design feels a bit visually unclear and interferes with other UI elements in the background. Additionally, it doesn’t seem to leverage the theme’s generated accent color.

To address this, I’ve edited the css to update the design for the Workspace Switcher OSD specifically for the **solid** version of the theme `WhiteSur-Dark-Green`. My version mirrors the aesthetics of the existing media OSDs for a consistent visual style while also incorporating the accent color to align better with the theme's overall design: 

![Image](https://github.com/user-attachments/assets/62bc35b9-4d6b-47c5-90a2-ee7d69097d90)

I am noob so I don't know how this will be incorporated into the theme generator but _I guess the accent color will be added as per the choice at the time of theme generation?_ Anyways, here’s the CSS code for the Workspace Switcher OSD, that I have edited in the `cinnamon.css` file in the theme, for my proposed design:

```css
.workspace-osd {  
  text-shadow: black 5px 5px 5px;  
  font-weight: bold;  
  font-size: 48pt;  
}  

.workspace-switch-osd {  
  min-width: 140px;  
  margin-bottom: 5em;  
  background-color: rgba(26, 26, 26, 0.96);  
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.08);  
  border: 1px solid black;  
  border-radius: 9999px;  
  font-weight: bold;  
  padding: 12px 36px 0 36px;  
}  

.workspace-switch-osd-indicator-box {  
  spacing: 12px;  
}  

.workspace-switch-osd-indicator {  
  background-color: rgba(255, 255, 255, 0.5);  
  padding: 3px;  
  margin: 12px;  
  border-radius: 32px;  
}  

.workspace-switch-osd-indicator:active {  
  background-color: #79B757;  
  padding: 6px;  
  margin: 12px;  
}  
```
I am just offering this css as an _example_ to explain how it should look, since Idk if this is the right/best way to do it. I'll leave the exact implementation upto your expertise.

I hope you find this suggestion helpful and aligned with your vision for the WhiteSure theme. Please let me know if you’d like me to refine or further discuss the proposal.

Thank you once again for your excellent work!
