### ISSUE TITLE
Monterey Firefox theme: allow to drag headerbar empty space

### ISSUE THREAD

**Issue by rivanfebrian123** [vinceliuice/WhiteSur-gtk-theme#323]
Unlike that GNOMISH feature, it only allows empty space dragging and buttons on the address bar container. Here's my current code, but I don't know where to put this :D
```css
/* Add your own custom styles here */

:root[tabsintitlebar] #nav-bar .chromeclass-location {
	-moz-window-dragging: drag;
}

```
