### ISSUE TITLE
[Idea] Left alignment of close button on tabs

### ISSUE THREAD

**Issue by ollieatkinson** [vinceliuice/WhiteSur-gtk-theme#399]
Safari places the close button on the left: 
![image](https://user-images.githubusercontent.com/88668746/129805491-19c6569f-681d-4431-8d9d-c75b5bbfd822.png)

To better mimic that behaviour this theme should also offer that as an option as currently it right-aligns the button

I found some examples of others attempting this with their own themes but I was unable to apply those changes to this theme. (https://support.mozilla.org/en-US/questions/1157451)

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
These codes are too old and can no longer works now, I tested it not works

**Comment by oliveratkinson-bc** [comment]
I see, is there documentation for the latest versions of firefox and the css for tabs? It would be a really nice thing to add in

**Comment by vinceliuice** [comment]
I am also looking for it, but unfortunately I haven't found it yet

**Comment by victormihalache** [comment]
This (on a clean FF installation) inverts the order from "favicon-title-close" to "close-title-favicon". I haven't found a way to not move the favicon yet.

```css
.tab-content{ direction: rtl }
.tab-label-container,
.tab-icon-stack{ direction: ltr }
.tab-close-button{ padding-inline: 7px !important; width: unset !important; }
```

**Comment by vinceliuice** [comment]
Thanks! @victormihalache that help a lot

**Comment by victormihalache** [comment]
Haven't tested this, does it work? (should move only the 'x'

```
.tab-close-button{
      padding-inline: 7px !important;
      width: unset !important;
      -moz-box-ordinal-group: 0;
}
```

**Comment by oliveratkinson-bc** [comment]
@victormihalache The first solution you posted is close, as it left aligns the close - though, this would be good to be tight to the edge of the tab rather than centered.

The second solution does not align the close button, it remains on the right. Out of curiosity, where can you find information about the class selectors?

**Comment by oliveratkinson-bc** [comment]
This seems to give me the results I expect:

```css
.tab-content{ flex-direction: row }
.tab-close-button{ order: 1 }
.tab-icon-stack{ order: 2; margin-left: auto;  }
.tab-label-container{ order: 3; margin-right: auto;  }
```

It does however directly conflict with some of the values in the theme currently: 
- https://github.com/vinceliuice/WhiteSur-gtk-theme/blob/master/src/other/firefox/WhiteSur/parts/tabsbar.css#L122
