### ISSUE TITLE
Apple icon in topbar shell theme

### ISSUE THREAD

**Issue by alexbode** [vinceliuice/WhiteSur-gtk-theme#48]
How to remove the apple icon in the topbar all the way to the left when using the shell theme? Where does the svg/png live in this repo?

**Comment by alexbode** [comment]
Im using this extension to remove the apple icon for the time being. `https://extensions.gnome.org/extension/744/hide-activities-button/`

**Comment by mdragossh** [comment]
> How to remove the apple icon in the topbar all the way to the left when using the shell theme? Where does the svg/png live in this repo?

adress in my case /usr/share/themes/WhiteSur-dark/gnome-shell/ you have file gnome-shell.css
you should comment this part in your gnome-shell.css
```css
/*
#panel #panelActivities.panel-button > * {
  background-image: url("assets/activities.svg");
  background-position: center top;
  background-size: 18px 18px;
  width: 24px;
  height: 24px;
  background-color: transparent !important;
  background-gradient-direction: none !important;
  border: none;
  color: transparent;
}*/
```
