### ISSUE TITLE
[Fix included] Green border on Dash to Dock notification count badges

### ISSUE THREAD

**Issue by edwinvandeven** [vinceliuice/WhiteSur-gtk-theme#56]
In Dash to Dock I noticed a green border around the notification badges. In the Yaru theme I found a fix for this. Screenshots showing the difference are attached and the CSS from Yaru is listed below.

By adding the following to gnome-shell.css the border can be removed:

```css
#dashtodockContainer .number-overlay {
  color: white;
  background-color: rgba(0, 0, 0, 0.8);
  text-align: center; 
}

#dashtodockContainer .notification-badge {
  color: white;
  background-color: #0c6d1a;
  padding: 0.2em 0.5em;
  border-radius: 1em;
  border: 1px solid #073f0f;
  box-shadow: -1px 1px 5px 0px rgba(0, 0, 0, 0.5);
  font-weight: bold;
  text-align: center;
  margin: 2px; 
}
```

Before
![Screenshot from 2020-10-23 23-50-05](https://user-images.githubusercontent.com/7576685/97057050-b322bb00-158a-11eb-91e7-ace0d8d700b1.png)

After
![Screenshot from 2020-10-23 23-50-19](https://user-images.githubusercontent.com/7576685/97057057-b7e76f00-158a-11eb-826d-f3fe4f2c3767.png)
