### ISSUE TITLE
Firefox autoscroll icon glitched (WhiteSur)

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#784]
Currently, the firefox autoscroll icon (when you click middle mouse) is glitched
![image](https://user-images.githubusercontent.com/85798751/214052876-4700a6dd-92d3-47f3-b896-7dd5be2262e9.png)
Using the following code it can be made to look like this:
![image](https://user-images.githubusercontent.com/85798751/214053104-8853b9f1-95af-468e-b660-94cc4318e136.png)
```css
.autoscroller {
  --panel-background: transparent !important;
  --panel-border-color: transparent !important;
  background: #fff url("chrome://global/skin/icons/autoscroll.svg") no-repeat center !important;
  border-radius: 50% !important;
}
```

With the following lines of code, separate icons are used depending on the scroll direction
```css
.autoscroller {
    --panel-background: transparent !important;
    --panel-border-color: transparent !important;
    background: #fff url('chrome://global/skin/icons/autoscroll.svg') no-repeat center !important;
    border-radius: 50% !important;
}
.autoscroller[scrolldir='NS'] {
    background-image: url('chrome://global/skin/icons/autoscroll-vertical.svg') !important;
}
.autoscroller[scrolldir='EW'] {
    background-image: url('chrome://global/skin/icons/autoscroll-horizontal.svg') !important;
}
```
### Vertical: 
![image](https://user-images.githubusercontent.com/85798751/214053753-f8dee6f8-c1ba-4a5a-9161-3ee589627a03.png)

### Horizontal
![image](https://user-images.githubusercontent.com/85798751/214054061-bbb3d52c-394f-4b08-9ba1-7650021403b7.png)

### Horizontal and  vertical
![image](https://user-images.githubusercontent.com/85798751/214053961-f9911789-1027-4f22-8e85-ea617ca7ed78.png)

I didn't test this on light theme so maybe a different color should be used for the background but at least the icon looks normal this way
