### ISSUE TITLE
Firefox WhiteSur dropdown makes screen shift

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#785]
In Firefox using the WhiteSur theme, when opening a dropdown, the entire screen shifts down slightly
![image](https://user-images.githubusercontent.com/85798751/214055597-52da3f18-6bdd-4d4f-badd-bf0b2f327ee3.png)
<br>
A small bar sticks out above the url / header bar
![image](https://user-images.githubusercontent.com/85798751/214055640-4c406c48-4663-42c4-a267-d8f78d05705d.png)

Screen recording:
![ezgif-2-5200875116](https://user-images.githubusercontent.com/85798751/214056302-93aa24e2-7e31-4c17-a9df-6914025c72c5.gif)
For some reason the screen recording doesn't show the dropdown options but I was opening and closing it

Problem is fixed by removing `menulist,` from
```css
/* Text buttons */
menulist,
.subviewbutton.panel-subview-footer,
.panel-footer button,
#downloadsHistory,
#overflowMenu-customize-button,
#appMenu-popup .panel-banner-item,
#appMenu-zoomReset-button:not(#appMenu-fxa-label):not(#hack),
#appMenu-popup #appMenu-zoomReset-button2:not(#hack),
#tracking-protection-preferences-button:not(#hack),
.findbar-container toolbarbutton.findbar-button,
.notification-button,
.protections-popup-footer-button,
#PanelUI-panic-view-button,
.tracking-protection-button,
.dialog-button,
.autocomplete-richlistitem[type="loginsFooter"],
.dialog-button-box button,
.toolbaritem-combined-buttons:is(:not([cui-areatype="toolbar"]),
[overflowedItem="true"]) > #appMenu-fxa-label2:not(#hack),
.button.connect-device,
#item-choose button,
#editBMPanel_newFolderButton {
	padding: 2px 10px !important;
	text-align: center !important;
}
```
in `WhiteSur/parts/buttons.css`
