### ISSUE TITLE
Firefox single tab option leaves black bar

### ISSUE THREAD

**Issue by AI-ien** [vinceliuice/WhiteSur-gtk-theme#787]
Code located in hide-single-tab.css. I tried with code below that works on default theme, but not with yours. There is something about tabs below nav bar that I don't understand

```css
#TabsToolbar tab[first-visible-tab="true"][last-visible-tab="true"]{
  visibility: collapse !important;
  min-height: 0 !important;
  height: 0;
}
```

**Screen with two tabs**

![Screenshot_20230127_100626](https://user-images.githubusercontent.com/33252703/215038149-ef1f67b4-f8bd-4324-a4fb-de83a7e62288.png)

**Screen one tab**

![Screenshot_20230127_100659](https://user-images.githubusercontent.com/33252703/215038257-7d0140b5-e2a7-4edc-a164-329a18a54bd2.png)
