### ISSUE TITLE
Issues with firefox 113

### ISSUE THREAD

**Issue by FelixFourcolor** [vinceliuice/WhiteSur-gtk-theme#869]
I just updated from firefox 112 to 113, and the whitesur theme for it became wonky.

This is the default version.
![Screenshot from 2023-05-09 12-51-06](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/e010b384-e674-4af7-a7c6-939183d52381)

Monterey version. I'm running multiple tabs, Ctrl + Tab does switch between them, but there are no indicators that the other ones are running.
![Screenshot from 2023-05-09 12-56-05](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/e3ad18b5-43ed-489b-a51b-af2a75c40037)

Alt version.
![Screenshot from 2023-05-09 12-58-27](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/34260584/13b7e1e1-2168-4e24-9630-5fc6076fe2b6)

System info:
- Arch
- Gnome 44.1
- Latest version of WhiteSur-gtk-theme at the moment (just did a `git pull` and reinstall before filing this report)

**Comment by FelixFourcolor** [comment]
Clarification: I was running multiple tabs only when testing the monterey version. The default and alt version *correctly* show only one tab.

I should've been consistent with the number of tabs as I tested different versions, but it's too late now. I hope this clarification makes it clear.

**Comment by kugelvlitz** [comment]
Just upgraded Firefox, having the same issue

**Comment by BYT0723** [comment]
![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/59989961/d3699bee-07c4-4987-b482-4bad67961fa5)
It looks like there is no tab, in fact it just goes where you can't see it.
![图片](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/59989961/f7795f20-4401-4206-b76d-d7d48075479a)

**Comment by shine-Diamond-295** [comment]
same issue

**Comment by lilbudek** [comment]
I have the same problem. I rolled back to 112

**Comment by FelixFourcolor** [comment]
@vinceliuice Thank you so much for the quick fix!

**Comment by kugelvlitz** [comment]
Great work as always, thanks for the fix!

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by vinceliuice** [comment]
Still have no idea how to fix the align issue

**Comment by vinceliuice** [comment]
I can only set the label to center, but can not change icon's position

**Comment by Fedex159** [comment]
> I can only set the label to center, but can not change icon's position

Hi, try to add this to **customChrome.css** (remove the styles you don't want)

```css
/* Add your own custom styles here */

#urlbar #urlbar-input-container #urlbar-input {
  text-align: left !important;
}

.tab-label {
  margin: 0 auto !important;
}

#tabbrowser-tabs,
#tabbrowser-tabs arrowscrollbox {
  max-height: 40px !important;
  --tab-min-height: 40px !important;
}

.tab-label-container {
  max-width: min-content !important;
}
```

![Captura desde 2023-05-10 19-07-00](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/44141208/4c82c2f2-eb9f-4c3e-90bf-ebd46d2ae81a)
