### ISSUE TITLE
TitleBarButton are too small and can't find a way to modify it... 

### ISSUE THREAD

**Issue by UnderNowhere** [vinceliuice/WhiteSur-gtk-theme#918]
**Hi there!**

I have a problem with the titlebarbutton which are too small. Compared on the image they are ultra small compared to the firefox buttons. 

I've tried to fix the problem with GTK.css but I can't find the right flag and I've tried a lot of classes but nothing changes... 
My laptop screen resolution is 1440p, so maybe that's the problem. I was wondering if I could change the assets in the theme file to higher resolutions, that would fix the problem...

If you have a solution it would be great! 

Thanks in advance!

![Screenshot from 2023-08-12 12-36-12](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/115153570/31df3e09-e18c-4221-a2d5-19dcf054b5f9)

![Screenshot from 2023-08-12 12-28-04](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/115153570/0c4f484a-eb08-4f26-b3f0-fcfabb60a93f)

**Comment by UnderNowhere** [comment]
Sure, here's the content you provided turned into a Markdown (`.md`) file:

# How to Resize Titlebar Buttons in WhiteSur GTK Theme

If you're looking to adjust the size of titlebar buttons in the WhiteSur GTK theme, follow these step-by-step instructions to achieve the desired look.

## 1. Prepare the Assets

- Navigate to the WhiteSur-gtk-theme folder.
- Open the path `/src/assets/gtk/windows-assets`.

## 2. Customize Title Button Icons

Before making any changes, create backups of the theme's title button icons.

- Locate your current title button folder (e.g., `titlebutton-alt`, `titlebutton-nord`) and back it up.
- Delete all `.png` files within the title button folder.

## 3. Modify Rendering Settings

- Return to the `windows-assets` folder.
- Open the `render-assets.sh` script corresponding to your chosen theme.
- For each `<else>` branch, add the following lines:

```shell
--export-width=64 --export-height=64 \ # for the default .png
--export-width=128 --export-height=128 \ # for the @2.png
```

- Edit the `--export-dpi` flag, setting it to `300`:

```shell
--export-dpi=300 \
```

- Save the file and execute it in your terminal using:

```shell
./render-assets.sh
```

## 4. Reinstall WhiteSur Theme

Reinstall the WhiteSur GTK theme. Use the following command (include the `-l` flag):

```shell
./install.sh -t all -m -N glassy -s 220 -l --normal --round -HD -p bigger
```

## 5. Adjust CSS Files

Open the `gtk-Dark.css` or `gtk-Light.css` file in either of these paths:

- `/home/user-name/.config/gtk-4.0/gtk-Dark.css`
- `/home/user-name/.config/gtk-4.0/gtk-Light.css`

Locate the section related to the titlebar buttons:

```css
windowcontrols button.close,
windowcontrols button.maximize,
windowcontrols button.minimize {
  min-width: 16px;
  min-height: 16px;
  margin: 0;
  padding: 0;
  background-position: center;
  background-repeat: no-repeat;
  background-size: 16px 16px;
}
```

Modify the `min-width`, `min-height` values, and add a `border-radius` property for a smooth appearance. For example:

```css
windowcontrols button.close,
windowcontrols button.maximize,
windowcontrols button.minimize {
  min-width: 24px;
  min-height: 24px;
  margin: 0;
  padding: 0;
  background-position: center;
  background-repeat: no-repeat;
  background-size: 24px 24px;
  border-radius: 100%;
}
```

Create or open the `/home/user-name/.config/gtk-3.0/gtk.css` file and insert the following code, replacing `<size>` with your desired button size:

```css
windowcontrols button.close,
windowcontrols button.maximize,
windowcontrols button.minimize {
  min-width: <size>px;
  min-height: <size>px;
  margin: 0;
  padding: 0;
  background-position: center;
  background-repeat: no-repeat;
  background-size: <size>px <size>px;
  border-radius: 100%;
}
```

## 6. Apply Changes and Restart

- Save all modified files.
- Log out of your session and log back in to see the changes take effect.

With these steps, you've successfully resized the titlebar buttons in the WhiteSur GTK theme to your preferred size. Enjoy your customized user interface!

### Feel free to adjust the phrasing and formatting further to match your style and preferences.
