### ISSUE TITLE
Firefox WhiteSur autoscroller glitch + fix

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#931]
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/8db23e32-af2e-42a9-b70a-94e39d49cdb4)

This is what the autoscroll icon with middle click looks like in Firefox. It looks glitched because the image is repeating and the padding is incorrect. You can fix it with the following code, this also adds vertical or horizontal directions icons based on the direction.
```css
.autoscroller {
        --panel-background: transparent !important;
	--panel-border-color: transparent !important;
	background: #fff url('chrome://global/skin/icons/autoscroll.svg') no-repeat center !important;
	border-radius: 50% !important;
	padding: 0 !important;
}
.autoscroller[scrolldir='NS'] {
	background-image: url('chrome://global/skin/icons/autoscroll-vertical.svg') !important;
}
.autoscroller[scrolldir='EW'] {
	background-image: url('chrome://global/skin/icons/autoscroll-horizontal.svg') !important;
}
```

This is what it looks like with the new code:
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/9e1ef247-e571-43ea-9906-6fa87e8bf0d1)
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/fbb313cc-1f1e-4de8-b3ff-4c34720d4031)
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/d26d7b88-63a8-4fab-bc50-9ab8446b752c)

Feel free to change or not use my code at all, just a suggestion :) thanks for the theme
