### ISSUE TITLE
Activities icon disappeared (Gnome 45)

### ISSUE THREAD

**Issue by fernandesafp** [vinceliuice/WhiteSur-gtk-theme#956]
I ran `sudo ./tweaks.sh -r -g` in order to remove the activities icon and get the Gnome 45 workspace indicator. Now the icon disappeared and I can't seem to get the indicator on.

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/0bbbe02d-546c-44f7-8542-7cb500f71753)

Edit: Unfortunately #953 did not work for me.

**Comment by fernandesafp** [comment]
I can get the icons back by reinstalling, but never the workspace indicator (I had it before installing this theme).

**Comment by fernandesafp** [comment]
I noticed my Yaru themes still had the workspace indicator on, so I fixed it by running `./tweaks.sh -g -r` and commenting out on `gnome-shell.css`:

```css
/*
#panel .panel-button#panelActivities {
  -natural-hpadding: 8px;
  background-image: url("assets/activities.svg");
  background-position: center center;
  background-size: 24px 24px;
  width: 24px;
  height: 24px;
  background-gradient-direction: none;
  border: none;
  color: transparent;
  font-size: 0;
}


#panel .panel-button#panelActivities > * {
  width: 32px;
}

#panel .panel-button#panelActivities StBoxLayout {
  spacing: 0;
}

#panel .panel-button#panelActivities .workspace-dot {
  background-color: transparent;
}

#panel .panel-button#panelActivities:active, #panel .panel-button#panelActivities:overview, #panel .panel-button#panelActivities:focus, #panel .panel-button#panelActivities:checked {
  border: none;
  color: transparent;
}

#panel .panel-button#panelActivities:overview {
  background-color: transparent;
}
*/
```

And adding:

```css
#panel .panel-button#panelActivities {
  -natural-hpadding: 15px;
}

#panel .panel-button#panelActivities StBoxLayout {
  spacing: 5px;
}

#panel .panel-button#panelActivities .workspace-dot {
  border-radius: 999px;
  min-width: 8px;
  min-height: 8px;
  background-color: #f2f2f2;
}
```

Now, if I want the GDM theme, once I run `./tweaks.sh -g`, the icons are overlapped like so:

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/cfcff033-97d6-4566-aa2d-7d08b5d48a85)

This happens regardless of the shell theme I choose. The workaround for this is to replace the `src/assets/gnome-shell/activities/activities.svg` with a transparent icon, as mentioned in #948 (and reinstall everything).

![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/71726270/858828a4-d72e-4936-84c2-4d27c3e99618)
