### ISSUE TITLE
Firefox 119 WhiteSur theme active tab color broken

### ISSUE THREAD

**Issue by Laurens256** [vinceliuice/WhiteSur-gtk-theme#963]
In Firefox 119, the highlight color of the active tab is not set correctly anymore
![image](https://github.com/vinceliuice/WhiteSur-gtk-theme/assets/85798751/41625932-91b1-4863-b263-0733f0b32bd6)
In this image, github is my active tab.

~~This is because the `selected` attribute is not set on `.tab-background` anymore, just its parent `.tabbrowser-tab`~~

Correction: the attribute is still set on `.tab-background` but it gets set as `selected=""`, not `selected="true"`. The fix below still works but you could also change it so `selected` is checked without true value

**Comment by Laurens256** [comment]
Also, after fixing this using the following code in `tabsbar.css`
```css
.tabbrowser-tab[selected] .tab-background {
	background-color: var(--gnome-tabbar-tab-active-background) !important;
	background-image: none !important;
	border: none !important;
	border-image: none !important;
	transition: none !important;
	margin-left: -1px !important;
	margin-right: -1px !important;
	border-radius: 0 !important;
	box-shadow: 1px 0 var(--gnome-toolbar-border-color), 1px 0 3px rgba(0, 0, 0, 0.08),
	            -1px 0 var(--gnome-toolbar-border-color), -1px 0 3px rgba(0, 0, 0, 0.08),
	            inset 0 -1px var(--gnome-toolbar-border-color) !important;
}

.tabbrowser-tab[selected] .tab-background:-moz-window-inactive {
	background-color: var(--gnome-inactive-tabbar-tab-active-background) !important;
	border-image: none !important;
}
```

The hover state for the active tab is kind of broken. It gets the same hover state as the non active tabs. My fix for this is to change:
`#TabsToolbar .tabbrowser-tab:hover > .tab-stack > .tab-background:not([selected=true])`

to this
`#TabsToolbar .tabbrowser-tab:not([selected=true]):hover > .tab-stack > .tab-background`
